Generate material library doc by script
flexcompute-readthedocs/tidy3d-docs pull request #74
Opened 2022-11-29 08:39 UTC by xin-flex

Added script "docs/generate_doc.py" to generate "docs/source/material_library.rst", which is executed in "docs/source/conf.py".

2022-11-29 09:02 UTC, tylerflex requested changes
Wow, this must have been a lot of work. thanks for including this, it's going to be much improved.

Material library compiles well locally. there are several warnings in the compilation though, seems like dozens of the following warnings

```
/Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/source/material_library.rst:3: WARNING: Duplicate explicit target name: "[data]".
/Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/source/material_library.rst:3: WARNING: Duplicate explicit target name: "[doi]".
/Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/source/material_library.rst:79: WARNING: Blank line required after table.
```

Perhaps some are related to the data / dot links? Let's see if we can somehow get around these warnings?

2022-11-29 09:02 UTC, tylerflex commented on docs/generate_doc.py
> +    main()
add newline to end of file.

2022-11-29 10:05 UTC, tylerflex commented
One other thing you might want to consider if you have the energy for it is to add a short code example for each variant / material, showing the exact syntax needed to import the medium, for example, for mat "mat" and variant "var" it could look like

```
>>> mat = material_library[mat][var]
```

2022-11-29 19:38 UTC, weiliangjin2021 commented
Very impressive work!

- Near the top of the page, below "To import a material “mat” with variant “var” as a tidy3d medium:", can we also comment that one can import the default variant with `medium = material_library['mat']`?
- Below `print(material_library['Ag'].variants.keys())`, how about mention that one can access the details of the variants via `material_library['Ag'].variants['var']`?
- Regarding the table, when the number of variants is larger than the number of the reference, it doesn't look so straightforward to find out the reference for the variant. Numbered reference lists and place the number next the variant can be helpful. But maybe it's good enough for now.

2022-11-30 17:40 UTC, weiliangjin2021 commented
One more question: how are the materials ordered in the material_library doc page? They are not in the alphabetic order.

2022-12-02 19:49 UTC, xin-flex commented
> Wow, this must have been a lot of work. thanks for including this, it's going to be much improved.
> 
> Material library compiles well locally. there are several warnings in the compilation though, seems like dozens of the following warnings
> 
> ```
> /Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/source/material_library.rst:3: WARNING: Duplicate explicit target name: "[data]".
> /Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/source/material_library.rst:3: WARNING: Duplicate explicit target name: "[doi]".
> /Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/source/material_library.rst:79: WARNING: Blank line required after table.
> ```
> 
> Perhaps some are related to the data / dot links? Let's see if we can somehow get around these warnings?

This is because multiple material models could reference a same paper. Currently each material's section has its own list of references. One option is to consolidate all references to the end of the page, and reference to it in each material section. I can give it a try to see how it looks.

2022-12-02 19:50 UTC, xin-flex commented on docs/generate_doc.py
> +    C_0 = 299792458 * 1e6 # um/s
I can do that

2022-12-02 19:51 UTC, xin-flex commented on docs/generate_doc.py
> +                    wl = C_0 / (freq * 1e12) # um
got it

2022-12-02 19:51 UTC, xin-flex commented on docs/generate_doc.py
> +    main()
got it

2022-12-02 19:52 UTC, xin-flex commented
> add a short code example for each material or variant, showing the exact syntax needed to import the medium, for example, for material "mat" and variant "var" it could look like

Good point!. Let me try to see how it looks.

2022-12-02 19:53 UTC, weiliangjin2021 commented
> One option is to consolidate all references to the end of the page, and reference to it in each material section. I can give it a try to see how it looks.

Personally, I prefer the current style since each material only has a few references to display. Putting all references to the end makes hard to scroll back and forth. But not sure how others think.

2022-12-02 19:55 UTC, xin-flex commented
> Very impressive work!
> 
> * Near the top of the page, below "To import a material “mat” with variant “var” as a tidy3d medium:", can we also comment that one can import the default variant with `medium = material_library['mat']`?
> * Below `print(material_library['Ag'].variants.keys())`, how about mention that one can access the details of the variants via `material_library['Ag'].variants['var']`?
> * Regarding the table, when the number of variants is larger than the number of the reference, it doesn't look so straightforward to find out the reference for the variant. Numbered reference lists and place the number next the variant can be helpful. But maybe it's good enough for now.

Good points! I will add the first too.

For the table and reference, combined w a previous suggestions from Tyler, I think I will try to put all reference to the end of page and use numbered reference. Let me see how it looks.

2022-12-02 19:56 UTC, xin-flex commented
> One more question: how are the materials ordered in the material_library doc page? They are not in the alphabetic order.

Probably just the order in the material_library.py.

I can sort them in alphabetical order.

2022-12-02 19:57 UTC, xin-flex commented
> > One option is to consolidate all references to the end of the page, and reference to it in each material section. I can give it a try to see how it looks.
> 
> Personally, I prefer the current style since each material only has a few references to display. Putting all references to the end makes hard to scroll back and forth. But not sure how others think.

Ok... let me think about it
Also if Tyler have any thoughts feel free to comment.

2022-12-02 20:20 UTC, tylerflex commented
I think i like the original style too. Is there a way to disable sphinx
warnings like this?

On Fri, Dec 2, 2022 at 8:57 PM xin-flex ***@***.***> wrote:

> One option is to consolidate all references to the end of the page, and
> reference to it in each material section. I can give it a try to see how it
> looks.
>
> Personally, I prefer the current style since each material only has a few
> references to display. Putting all references to the end makes hard to
> scroll back and forth. But not sure how others think.
>
> Ok... let me think about it
> Also if Tyler have any thoughts feel free to comment.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/74#issuecomment-1335767555>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWDVXGA6AU4X64WYO3VURRDWLJICRANCNFSM6AAAAAASOGSKME>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-12-03 05:36 UTC, xin-flex commented
Updates are pushed. Please review. I addressed all comments other than disabling the sphinx warnings of duplicate explicit targets.

2022-12-03 09:25 UTC, tylerflex commented
Thanks. I think we should fix the sphinx warnings. Maybe this is worth a shot:
https://github.com/sphinx-doc/sphinx/issues/3921
Basically put two underscores after the link instead of 1 to make it an "anonymous reference".

Having a clean sphinx build isn't totally necessary for the docs compiling well, but it's good to keep a standard that there are no warnings or errors because otherwise they can add up quickly and we might miss some that are actually important to address.

2022-12-03 09:59 UTC, xin-flex commented
> Thanks. I think we should fix the sphinx warnings. Maybe this is worth a shot: [sphinx-doc/sphinx#3921](https://github.com/sphinx-doc/sphinx/issues/3921) Basically put two underscores after the link instead of 1 to make it an "anonymous reference".
> 
> Having a clean sphinx build isn't totally necessary for the docs compiling well, but it's good to keep a standard that there are no warnings or errors because otherwise they can add up quickly and we might miss some that are actually important to address.

Good point! Thanks for finding the link! Just fixed it.

2022-12-03 10:17 UTC, tylerflex commented
Great!

2022-12-04 05:27 UTC, weiliangjin2021 commented
Just one last place to change: since we have renamed Rakic1998 in several places to Rakic1998BB, the example at the top `silver = material_library['Ag']['Rakic1998']` need to be updated to Rakic1998BB

2022-12-04 05:28 UTC, weiliangjin2021 approved these changes

2022-12-05 23:33 UTC, merged